replicaCount: 1

deployment:
  name: inventory

image:
  repository: rsocontainerregistry.azurecr.io/inventory
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  AUTHENTICATION_URL: "http://web-auth:8000"
  MONGO_URI: "mongodb+srv://mongodb:galjetaksef123!@mongoloidgal.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"


