apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: rsocontainerregistry.azurecr.io/inventory:latest
        ports:
        - containerPort: 3000
        env:
        - name: AUTHENTICATION_URL
          value: "http://web-auth:8000"
        - name: MONGO_URI
          value: "mongodb+srv://mongodb:galjetaksef123!@mongoloidgal.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"


